// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZYRA.Attendance.Infrastructure;

#nullable disable

namespace ZYRA.Attendance.Infrastructure.Migrations
{
    [DbContext(typeof(AttendanceDbContext))]
    partial class AttendanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZyraHangfireModels.Models.AttendanceLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AttendanceState")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CheckTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("AttendanceLogs");
                });

            modelBuilder.Entity("ZyraHangfireModels.Models.AttendancePolicyMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("bit");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PolicyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AttendancePolicyMasters");
                });

            modelBuilder.Entity("ZyraHangfireModels.Models.AttendancePolicyRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttendancePolicyId")
                        .HasColumnType("int");

                    b.Property<string>("RuleCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RuleValue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AttendancePolicyId");

                    b.ToTable("AttendancePolicyRules");
                });

            modelBuilder.Entity("ZyraHangfireModels.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("userEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("ZyraHangfireModels.Models.EmployeeAttendancePolicy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttendancePolicyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AutoCheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AutoCheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeMappingId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AttendancePolicyId");

                    b.HasIndex("EmployeeMappingId");

                    b.ToTable("EmployeeAttendancePolicies");
                });

            modelBuilder.Entity("ZyraHangfireModels.Models.EmployeeMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttendancePolicyMasterId")
                        .HasColumnType("int");

                    b.Property<string>("BiometricUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HRMEmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCheckoutFinalOverriddenByHR")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExcludeFromBiometric")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastCheckoutFinal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LatestCheckoutFromBiometric")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AttendancePolicyMasterId");

                    b.ToTable("EmployeeMappings");
                });

            modelBuilder.Entity("ZyraHangfireModels.Models.HolidayMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HolidayCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HolidayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HolidayType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Holidiays");
                });

            modelBuilder.Entity("ZyraHangfireModels.Models.NavigationMenus", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MenuKey")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MenuLabel")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RequiredPermissionCode")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MenuId");

                    b.ToTable("NavigationMenus");

                    b.HasData(
                        new
                        {
                            MenuId = 1,
                            Description = "Executive overview and quick sync metrics",
                            DisplayOrder = 1,
                            IconName = "LayoutDashboard",
                            MenuKey = "dashboard",
                            MenuLabel = "Dashboard",
                            RequiredPermissionCode = "EMP_VIEW"
                        },
                        new
                        {
                            MenuId = 2,
                            Description = "Biometric device ID and employee code mapping",
                            DisplayOrder = 2,
                            IconName = "Users",
                            MenuKey = "employees",
                            MenuLabel = "Employees",
                            RequiredPermissionCode = "EMP_VIEW"
                        },
                        new
                        {
                            MenuId = 3,
                            Description = "HR administrators, permissions, and menu access matrix",
                            DisplayOrder = 3,
                            IconName = "ShieldCheck",
                            MenuKey = "hr-users",
                            MenuLabel = "User Access & HR",
                            RequiredPermissionCode = "USER_MANAGE"
                        },
                        new
                        {
                            MenuId = 4,
                            Description = "Immutable historical activity trail",
                            DisplayOrder = 4,
                            IconName = "FileText",
                            MenuKey = "audit-logs",
                            MenuLabel = "Audit Logs",
                            RequiredPermissionCode = "AUDIT_VIEW"
                        },
                        new
                        {
                            MenuId = 5,
                            Description = "Single API contract and Hangfire queue monitor",
                            DisplayOrder = 5,
                            IconName = "RefreshCw",
                            MenuKey = "zyra-api",
                            MenuLabel = "Hangfire & ZYRA API",
                            RequiredPermissionCode = "SYNC_TRIGGER"
                        },
                        new
                        {
                            MenuId = 7,
                            Description = "Global system and database parameters",
                            DisplayOrder = 7,
                            IconName = "Settings",
                            MenuKey = "settings",
                            MenuLabel = "Settings",
                            RequiredPermissionCode = "SYSTEM_SETTINGS"
                        },
                        new
                        {
                            MenuId = 8,
                            Description = "Global system attendance policies",
                            DisplayOrder = 3,
                            IconName = "Settings",
                            MenuKey = "attpolicy",
                            MenuLabel = "Attendance Policies",
                            RequiredPermissionCode = "SYSTEM_SETTINGS"
                        });
                });

            modelBuilder.Entity("ZyraHangfireModels.Models.Permissions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Category = "Employees",
                            Description = "View employee biometric mapping data",
                            PermissionCode = "EMP_VIEW",
                            PermissionName = "View Employees"
                        },
                        new
                        {
                            Id = 2L,
                            Category = "Employees",
                            Description = "Modify employee mapping and biometric exclusions",
                            PermissionCode = "EMP_EDIT",
                            PermissionName = "Edit Employees"
                        },
                        new
                        {
                            Id = 3L,
                            Category = "Attendance",
                            Description = "Override final employee checkout timestamp",
                            PermissionCode = "HR_OVERRIDE",
                            PermissionName = "HR Checkout Override"
                        },
                        new
                        {
                            Id = 4L,
                            Category = "Security",
                            Description = "Provision HR users, assign roleId, and manage credentials",
                            PermissionCode = "USER_MANAGE",
                            PermissionName = "Manage Users & Credentials"
                        },
                        new
                        {
                            Id = 5L,
                            Category = "Compliance",
                            Description = "Inspect system audit logs",
                            PermissionCode = "AUDIT_VIEW",
                            PermissionName = "View Audit Trail"
                        },
                        new
                        {
                            Id = 6L,
                            Category = "Integration",
                            Description = "Execute ProcessAttendanceSyncJob background job",
                            PermissionCode = "SYNC_TRIGGER",
                            PermissionName = "Trigger Hangfire Sync"
                        },
                        new
                        {
                            Id = 7L,
                            Category = "Settings",
                            Description = "Configure global system parameters",
                            PermissionCode = "SYSTEM_SETTINGS",
                            PermissionName = "System Configuration"
                        });
                });

            modelBuilder.Entity("ZyraHangfireModels.Models.RolePermissions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            PermissionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            PermissionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            PermissionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            PermissionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            PermissionId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            PermissionId = 7,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            PermissionId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 9,
                            PermissionId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 10,
                            PermissionId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 11,
                            PermissionId = 1,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 12,
                            PermissionId = 5,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 13,
                            PermissionId = 5,
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("ZyraHangfireModels.Models.Roles", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Full unrestricted system administration, user provisioning, and DB schema access",
                            IsActive = false,
                            RoleName = "Super Admin",
                            UpdatedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Employee management, HR overrides, and attendance log synchronization",
                            IsActive = false,
                            RoleName = "HR Admin",
                            UpdatedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Employee biometric verification and attendance reports monitoring",
                            IsActive = false,
                            RoleName = "Attendance Manager",
                            UpdatedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Read-only audit trail and SQL Server schema compliance inspector",
                            IsActive = false,
                            RoleName = "Auditor",
                            UpdatedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ZyraHangfireModels.Models.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SettingsName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SettingsValue")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("HRMSettings");
                });

            modelBuilder.Entity("ZyraHangfireModels.Models.Users", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPasswordResetRequired")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLoginDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ZyraHangfireModels.Models.AttendancePolicyRule", b =>
                {
                    b.HasOne("ZyraHangfireModels.Models.AttendancePolicyMaster", "AttendancePolicy")
                        .WithMany("Rules")
                        .HasForeignKey("AttendancePolicyId");

                    b.Navigation("AttendancePolicy");
                });

            modelBuilder.Entity("ZyraHangfireModels.Models.EmployeeAttendancePolicy", b =>
                {
                    b.HasOne("ZyraHangfireModels.Models.AttendancePolicyMaster", "AttendancePolicy")
                        .WithMany()
                        .HasForeignKey("AttendancePolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZyraHangfireModels.Models.EmployeeMapping", "EmployeeMapping")
                        .WithMany()
                        .HasForeignKey("EmployeeMappingId");

                    b.Navigation("AttendancePolicy");

                    b.Navigation("EmployeeMapping");
                });

            modelBuilder.Entity("ZyraHangfireModels.Models.EmployeeMapping", b =>
                {
                    b.HasOne("ZyraHangfireModels.Models.AttendancePolicyMaster", null)
                        .WithMany("EmployeeMappings")
                        .HasForeignKey("AttendancePolicyMasterId");
                });

            modelBuilder.Entity("ZyraHangfireModels.Models.AttendancePolicyMaster", b =>
                {
                    b.Navigation("EmployeeMappings");

                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
